"""empty message

Revision ID: 235bfc2d61bb
Revises: cf209a2be8a1
Create Date: 2020-03-28 00:32:48.282282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235bfc2d61bb'
down_revision = 'cf209a2be8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table('items_in_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_items_in_order_item_id_items')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_items_in_order_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items_in_order'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_in_order')
    op.drop_table('orders')
    # ### end Alembic commands ###
